import datetime, random
from direct.distributed.ClockDelta import *
from direct.distributed.DistributedObject import DistributedObject
from direct.fsm.FSM import FSM
from direct.gui.OnscreenText import OnscreenText
from direct.interval.IntervalGlobal import *
from panda3d.core import *
from toontown.toonbase import ToontownGlobals

class DistributedPrologueEvent(DistributedObject, FSM):
    notify = DirectNotifyGlobal.directNotify.newCategory('DistributedPrologueEvent')

    def __init__(self, cr):
        DistributedObject.__init__(self, cr)
        FSM.__init__(self, 'PrologueEventFSM')
        self.cr.prologueEvent = self
        cm = CardMaker('card')
        cm.setFrameFullscreenQuad()
        self.introCard = render2d.attachNewNode(cm.generate())
        self.introCard.setTransparency(1)
        self.introCard.setColorScale(0, 0, 0, 1)
        now = datetime.datetime.now()
        self.text = ('{0} years ago...').format(datetime.date.today().year - 2003)
        self.title = OnscreenText(text=self.text, pos=(0, 0), scale=0.15, font=ToontownGlobals.getSignFont(), fg=(1,
                                                                                                                  1,
                                                                                                                  1,
                                                                                                                  1), shadow=(0.1,
                                                                                                                              0.1,
                                                                                                                              0.1,
                                                                                                                              1))
        self.title.setColorScale(1, 1, 1, 0)
        self.description = OnscreenText(text='In the outskirts of Daisy Gardens...', pos=(0,
                                                                                          -0.75), scale=0.1, font=ToontownGlobals.getSignFont(), fg=(1,
                                                                                                                                                     1,
                                                                                                                                                     1,
                                                                                                                                                     1), shadow=(0.1,
                                                                                                                                                                 0.1,
                                                                                                                                                                 0.1,
                                                                                                                                                                 1))
        self.description.setColorScale(1, 1, 1, 0)
        self.laffMeter = base.localAvatar.laffMeter
        self.book = base.localAvatar.book.bookOpenButton
        self.book2 = base.localAvatar.book.bookCloseButton
        if random.randint(0, 100) < 5:
            self.eventMusic = base.loader.loadMusic('phase_14.5/audio/bgm/eggs/SB_alt.ogg')
        else:
            self.eventMusic = base.loader.loadMusic('phase_14.5/audio/bgm/SB_hub.ogg')

    def enterOff(self, offset):
        pass

    def exitOff(self):
        pass

    def __cleanupNPCs(self):
        pass

    def delete(self):
        self.demand('Off', 0.0)
        self.ignore('entercnode')
        self.__cleanupNPCs()
        DistributedObject.delete(self)

    def enterIdle(self, offset):
        pass

    def exitIdle(self):
        pass

    def enterEvent(self, offset):
        base.cr.playGame.hood.loader.music.stop()
        base.localAvatar.disableSleeping()
        base.localAvatar.invPage.ignoreOnscreenHooks()
        base.localAvatar.questPage.ignoreOnscreenHooks()
        introCard = self.introCard.colorScaleInterval(2, (0, 0, 0, 0))
        self.eventInterval = Sequence(Func(NodePath(self.book).hide), Func(NodePath(self.laffMeter).hide), Func(self.introCard.setColorScale, 0, 0, 0, 1), self.title.colorScaleInterval(2, (1,
                                                                                                                                                                                             1,
                                                                                                                                                                                             1,
                                                                                                                                                                                             1)), Wait(3), Func(base.camera.wrtReparentTo, render), Func(base.localAvatar.stopUpdateSmartCamera), Func(base.localAvatar.shutdownSmartCamera), Func(base.camera.setPosHpr, -143.552, -187.884, 99, -36.435, -10, 0), self.title.colorScaleInterval(2, (0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                      0)), Func(base.localAvatar.setPos, -27.565, 0, 21.384), Func(base.localAvatar.disableAvatarControls), Func(base.playMusic, self.eventMusic, looping=1, volume=1.2), Func(introCard.start), Func(camera.setPosHpr, -153.9, 71.375, 17.133, -118, 15.5, 0.0), Wait(0.2), Func(camera.setPosHpr, -1.295, 232.73, 232.5, -180, -34.0, 0.0), Wait(0.2), Func(camera.setPosHpr, 37.846, 227.13, 229.47, -211, -35.0, 0.0), Wait(0.2), Func(camera.setPosHpr, -111.0, -65.06, 127.82, -72.0, -37.0, 0.0), Wait(0.2), Func(camera.setPosHpr, 232.09, 179.4, 175.58, -240, -22.0, 0.0), Wait(0.2), Func(camera.setPosHpr, 29.36, -32.75, 24.134, -277, 3.0, 0.0), Wait(0.2), Func(camera.setPosHpr, 291.92, -58.5, 96.488, -283, -7.0, 0.0), Wait(0.2), Func(camera.setPosHpr, -93.65, -137.2, 35.397, -48, 1.5, 0.0), Wait(0.2), Func(camera.setPosHpr, 68.816, -52.84, 99.397, -307, 6.5, 0.0), Wait(0.2), Func(camera.setPosHpr, 3.4275, -321.5, 197.15, -358, -23.0, 0.0), Wait(0.2), Func(camera.setPosHpr, -69.71, -0.713, 11.123, -450, 42.5, 0.0), Wait(0.2), Func(base.camera.setPosHpr, -143.552, -187.884, 99, -36.435, -10, 0), Parallel(base.camera.posHprInterval(4, (115.847,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 -160.519,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 99), (40.188,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       -10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       0), blendType='noBlend'), self.description.colorScaleInterval(2, (1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1))), base.camera.posHprInterval(4, (115.847,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              192.455,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              99), (146.539,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    -10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0), blendType='noBlend'), Parallel(base.camera.posHprInterval(4, (-190.8777,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      137.415,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      99), (228.823,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            -10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            0), blendType='noBlend'), self.description.colorScaleInterval(2, (1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              0))), base.camera.posHprInterval(4, (-190.877,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   30), (270,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0), blendType='easeInOut'), Wait(1.269), base.camera.posHprInterval(3.75, (-42.69,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    21), (270,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0), blendType='easeInOut'), Func(base.localAvatar.displayTalk, "Ah, what a sunny day outside! Mayhaps I should go and see th' event ov'r in Toontown Central... what was it again?"), Wait(6), Func(base.localAvatar.displayTalk, "The elections? Bah! I have better things t' do!"), Wait(5), Func(base.localAvatar.displayTalk, "Perhaps I should see what Gyro's bin workin' on. I invested in his experiments, after all."), Wait(6), Func(base.localAvatar.attachCamera), Func(base.localAvatar.initializeSmartCamera), Func(base.localAvatar.startUpdateSmartCamera), Func(base.localAvatar.enableAvatarControls))
        self.eventInterval.start()
        self.eventInterval.setT(offset)

    def newSpeed(self, speed):
        intervals = [
         self.eventInterval]
        if speed:
            for interval in intervals:
                interval.setPlayRate(30)

        else:
            for interval in intervals:
                interval.setPlayRate(1)

    def exitEvent(self):
        self.eventInterval.finish()

    def enterEventTwo(self, offset):
        pass

    def exitEventTwo(self):
        pass

    def setState(self, state, timestamp):
        self.request(state, globalClockDelta.localElapsedTime(timestamp))