from panda3d.core import *
from toontown.battle.DistributedBattle import DistributedBattle
from direct.directnotify import DirectNotifyGlobal
from direct.interval.IntervalGlobal import *

class DistributedBattleSquirtingFlower(DistributedBattle):
    notify = DirectNotifyGlobal.directNotify.newCategory('DistributedBattleSquirtingFlower')

    def startTimer(self, ts=0):
        self.townBattle.timer.hide()

    def fadeScreen(self):
        seq = Sequence(Wait(5), Func(base.transitions.fadeOut))
        seq.start()

    def handleRewardDone(self):
        DistributedBattle.handleRewardDone(self)
        self.laffMeter = base.localAvatar.laffMeter
        self.extMusic = base.loader.loadMusic('phase_14.5/audio/bgm/SE_stinger_cogs_2.ogg')
        afterBattleSequence = Sequence(Wait(1), Func(base.playMusic, self.extMusic, looping=1, volume=1.1), Func(base.localAvatar.disableAvatarControls), Func(NodePath(self.laffMeter).hide), Func(base.localAvatar.obscureFriendsListButton, 1), Func(base.localAvatar.hideClarabelleGui), Func(base.localAvatar.invPage.ignoreOnscreenHooks), Func(base.localAvatar.questPage.ignoreOnscreenHooks), Func(NodePath(base.marginManager).hide), Func(base.localAvatar.stopUpdateSmartCamera), Func(base.localAvatar.shutdownSmartCamera), Func(base.localAvatar.setPos, -255.169, 224.169, -0.475), Func(base.localAvatar.setHpr, -180, 0, 0), Func(base.camera.setPosHpr, 0, 10, 3, -180, 0, 0), Func(base.localAvatar.displayTalk, "I haven't the faintest idea what these Robots are!"), Wait(7), Func(base.localAvatar.displayTalk, 'I need to warn my buddies about this.'), Wait(5.5), Func(base.localAvatar.displayTalk, 'Using Squirt to defeat these fellas, huh..'), Func(base.localAvatar.loop, 'run'), Func(self.fadeScreen), base.localAvatar.posHprInterval(6, (-255.169,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              204.169,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              -0.475), (-180,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        0)), Func(base.localAvatar.attachCamera), Func(base.localAvatar.initializeSmartCamera), Func(base.localAvatar.startUpdateSmartCamera), Func(NodePath(base.marginManager).show), Func(NodePath(self.laffMeter).show), Func(base.cr.prologue3Event.sendback))
        afterBattleSequence.start()